import imp
from api_promo.models.usuario_model import UsuarioModel
from api_promo.models.estabelecimento_model import EstabelecimentoModel
from api_promo.models.produto_model import ProdutoModel
from api_promo.models.promocao_model import PromocaoModel
from api_promo.models.usuario_estabelecimento_model import UsuarioEstabelecimentoModel
from api_promo.models.conquista_model import ConquistaModel
from api_promo.models.usuario_conquista_model import UsuarioConquistaModel
from api_promo.models.avaliacao_model import AvaliacaoModel
from api_promo.models.departamento_model import DepartamentoModel
from api_promo.models.curtida_model import CurtidaModel