import imp
from models.usuario_model import UsuarioModel
from models.estabelecimento_model import EstabelecimentoModel
from models.produto_model import ProdutoModel
from models.promocao_model import PromocaoModel
from models.usuario_estabelecimento_model import UsuarioEstabelecimentoModel
from models.conquista_model import ConquistaModel
from models.usuario_conquista_model import UsuarioConquistaModel
from models.avaliacao_model import AvaliacaoModel
from models.departamento_model import DepartamentoModel
from models.curtida_model import CurtidaModel